#!/bin/bash

if ! pgrep -x spotify >/dev/null; then
  echo ""; exit
fi

cmd="org.freedesktop.DBus.Properties.Get"
domain="org.mpris.MediaPlayer2"
path="/org/mpris/MediaPlayer2"

meta=$(dbus-send --print-reply --dest=${domain}.spotify \
  /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
  string:${domain}.Player string:Metadata)

parse() {
  local STR=$1
  echo "$meta" | sed -nr "$STR" | tail -1  | sed "s/\&/+/g" | \
    sed -E "s/(.{20}).*$/\1.../"
}

artist=`parse '/xesam:artist"/,+2s/^ +string "(.*)"$/\1/p'`
album=`parse '/xesam:album"/,+2s/^ +variant +string "(.*)"$/\1/p'`
title=`parse '/xesam:title"/,+2s/^ +variant +string "(.*)"$/\1/p'`

if [ -z "$artist" ]
then
  echo ""
else
  echo "$title - $artist"
fi
